@baseUrl = http://localhost:5500/api/v1

### SIGN UP (NEW USER)
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "name": "Shamir Khan",
    "email": "shamir@example.com",
    "password": "password123"
}

### SIGN IN (LOGIN)
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
    "email": "shamir@example.com",
    "password": "password123"
}

### GET ALL USERS (PROTECTED)
# After signing in, copy the token and put it below!
GET {{baseUrl}}/users
Authorization: Bearer <ADD_YOUR_TOKEN_HERE>

### GET CURRENT USER (PROTECTED)
GET {{baseUrl}}/users/65e9f8a... 
Authorization: Bearer <ADD_YOUR_TOKEN_HERE>

### SIGN OUT
POST {{baseUrl}}/auth/sign-out
